name: Create envfile

on: [ push ]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_TELEGRAM_BOT_API_TOKEN: "123"
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_NAME: ${{ secrets.DB_NAME }}
        envkey_DB_PASS: ${{ secrets.DB_PASS }}
        envkey_DB_PORT: ${{ secrets.DB_PORT }}
        envkey_DB_PORT_EXTERNAL: ${{ secrets.DB_PORT_EXTERNAL }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        directory: ./
        file_name: .env
        fail_on_empty: false
    - name: Download a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: env_container
        
